### ISSUE TITLE
Does micromon work with the WDC65C51 XMIT bug

### ISSUE THREAD

**Issue by maded2** [floobydust/Micromon#1]
Reference:  http://forum.6502.org/viewtopic.php?f=4&t=2543&start=30

I seem to get garbage on the output using WDC65C51.  It works using an UM6551 (although it sometime hangs).

thanks in advance.

EDIT: just realised you are the one on the above forum thread.

**Comment by floobydust** [comment]
Yes, I found the Xmit bug in the recently released W65C51. Micromon does not support the defective chip, as coding to make it work (in all cases) is a band-aid approach. The intent of Micromon is to support properly functioning hardware, mostly as a test case.
 In the above referenced thread, there's a simple delay routine which can be used instead or interrupt-driven transmit code. It does require you to change the loop iterations depending on CPU clock speed and ACIA baud rate.
 If you are getting intermittent hangs, you might have some noise issues or possibly running at a (CPU) clock speed that's too high for the circuitry, layout, one or more chips in the design etc. If you can reference a schematic for your design, I can take a look at it... and of course, any pictures of the completed system could help as well.
 Regards, KM

**Comment by maded2** [comment]
thanks for the confirmation.  I think the UM6551 is very sensitive to noise.  I am only running at 1Mhz but on the breadboard (waiting for the custom PCB from jlcpcb.com to produce my latest design with IRQ support).  Will test it when it arrives next week.

**Comment by floobydust** [comment]
I picked up some Rockwell CMOS parts a few years ago... R65C51P4 (4MHz parts) which have worked very well. I've not noticed any issues on a PCB layout. NOTE: I also have a more full featured monitor which you're welcome to try. It takes about 5KB of ROM space. I should probably add that to my Github account as well.
 Regards, KM

**Comment by maded2** [comment]
will love to try it.  I've 16k Rom space to use up.  I especially want xmodem support to download binaries to the 6502 from the PC.   btw, I ported micromon to use ca65, I can send you my changes.

**Comment by floobydust** [comment]
I'll dig it out... but you should download the source for the C02 Pocket SBC... the Monitor code contains everything, including Xmodem upload and download, a full 65C02 disassembler, the ability to program the EEPROM insitu and more. The only required change would be a different BIOS to support the 65C51 and 65C22 (for timer support).

**Comment by maded2** [comment]
just had a look at your Pocket SBC.  Very interesting.  switched to use SCC2691 is also very interesting.  just place order for some to try out for myself.  I think the UART & EEProm (28C256) is holding my board back to go beyond 6Mhz.   I see you are using 28HC256, so I ordered some of them as well.    Like to get to  8 or 10Mhz.   I will be working on the Video system next using the V9958 chip.  I aim to have a full standalone 6502 computer.

**Comment by floobydust** [comment]
So, keep in mind that the SCC2691 has a limit of around 6MHz... I have one chip which runs at 8MHz, but the design spec is basically 6MHz. Newer NXP UARTs can easily go past 16MHz.
 The AT28C256... standard speed is 150ns, but I've run those upwards of 10MHz without any issue, but they also make 70ns parts which should get you to 16MHz or possibly a bit faster, but that also relies on the rest of the circuitry. Start with a more reasonable clock speed, then start moving things up once you have a reliable running system. I would also recommend using a PLD for glue logic... take a closer look the AT22V10 I'm using on the Pocket SBC.
 Regards, KM

**Comment by maded2** [comment]
it does seem to go beyond 6Mhz required another level of design and parts.  I've been looking at CPLD, mainly Daryl Rictor design (http://sbc.rictor.org/decoder.html).  I've got some ATF22V10 & GAL22V10 to play with.  I will probably stay with 6Mhz until the video system is working before trying to go for higher clocks.  Many thanks for your advises.  Using your micromon will greatly help with prototyping & debugging the video system.

**Comment by floobydust** [comment]
I suggest looking my CPLD code... the overall function is similar to Daryl's, but uses some different definitions within WinCUPL (simpler).... and I like having a single I/O page at $FE00.
 I'll dig out the last Full monitor version that supports the 6551/6522 and get it uploaded. I also have a CMOS version of EnHanced Basic that also works with it. The current code for the C02 Pocket SBC has an updated CMOS EhBasic with Load and Save implemented and calls the C02 Monitor to use Xmodem upload/download. Also note that the Xmodem code all works with the console port. I use Serial (OSX app) and also ExtraPutty (Windows app) for testing of all Xmodem functions.
 Have fun with Micromon... neat little piece of code I cobbled down from my larger Monitor/BIOS project.
 Regards, KM
